# Generated by Django 5.1.4 on 2025-01-31 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_teacher_detail_alter_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
    ]
