# Generated by Django 5.1.4 on 2025-02-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_courserating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '7. Course Ratings'},
        ),
    ]
