# Generated by Django 5.1.4 on 2025-02-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_courserating_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '7. Course_rating'},
        ),
    ]
