# Generated by Django 5.1.4 on 2025-02-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_teacher_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='detail',
        ),
    ]
