# Generated by Django 5.1.4 on 2025-03-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_course_category_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
