# Generated by Django 5.1.4 on 2025-03-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_coursecategory_title_alter_teacher_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
