# Generated by Django 5.1.4 on 2025-03-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_student_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_text', models.TextField()),
                ('notif_for', models.CharField(max_length=200)),
                ('notif_created_time', models.DateTimeField(auto_now_add=True)),
                ('notifiread_status', models.BooleanField(default=False)),
            ],
        ),
    ]
