# Generated by Django 5.1.4 on 2025-03-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_notification_notif_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '5. Students'},
        ),
    ]
