# Generated by Django 5.1.4 on 2025-03-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '5. Student'},
        ),
    ]
