# Generated by Django 5.1.4 on 2025-03-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_student_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
