# Generated by Django 5.1.2 on 2025-03-29 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_attemptquiz_right_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquiz',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quiz'),
        ),
    ]
