# Generated by Django 5.1.2 on 2025-03-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_course_course_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_views',
            field=models.BigIntegerField(default=0),
        ),
    ]
