# Generated by Django 5.1.2 on 2025-04-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_student_otp_digit_student_varify_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='varify_status',
            new_name='verify_status',
        ),
    ]
