# Generated by Django 5.1.2 on 2025-04-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_rename_varify_status_student_verify_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='varify_status',
            new_name='verify_status',
        ),
    ]
