# Generated by Django 5.1.2 on 2025-04-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_rename_varify_status_teacher_verify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_via_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='login_via_otp',
            field=models.BooleanField(default=False),
        ),
    ]
