# Generated by Django 5.1.2 on 2025-04-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_teacher_login_via_otp_teacherstudentchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherstudentchat',
            old_name='msg_txt',
            new_name='msg_text',
        ),
    ]
